schema_version: 1

context:
  version: "2019.2.0"
  date: 20230719
  commit: 72129fd974f582bb1f7ed96121c3d216665c9ead

package:
  name: fenics-ffc
  version: ${{ version }}.dev${{ date }}

source:
  url: https://bitbucket.org/fenics-project/ffc/get/${{ commit }}.tar.gz
  sha256: 013426e23d0014a459dec697537a48b5173cdec4cdc66dbeb7eaa693120d2600
  patches:
    - ufc-include-path.patch
    - pr106.patch
    - setuptools82.patch

build:
  number: 2
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install --no-deps . -vv
    - mkdir -p $PREFIX/include
    - cp ffc/backends/ufc/*.h $PREFIX/include/

requirements:
  host:
    - python ${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy
    - fenics-dijitso ==2019.1.0
    - fenics-fiat ${{ version }}.dev*
    - fenics-ufl-legacy ==2022.3.0

tests:
  - python:
      imports:
        - ffc
        - ffc.backends
        - ffc.backends.dolfin
        - ffc.backends.ufc
        - ffc.errorcontrol
        - ffc.quadrature
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - ffc --help
      - test -f $PREFIX/include/ufc.h
      - test -f $PREFIX/include/ufc_geometry.h

about:
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: The FEniCS Form Compiler
  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (https://fenicsproject.org). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  homepage: https://www.fenicsproject.org
  repository: https://bitbucket.org/fenics-project/
  documentation: https://fenics.readthedocs.io

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
    - jan-janssen
